version: "3.5"

services:

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: always
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - ${PWD}/docker-configs/v1/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
    env_file: 
      - ${PWD}/docker-configs/v1/influxdb/influx.env      
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    networks:
      - web
      - db      

networks:
  web:
    external: true
  db:
    external: true        