version: "3.5"

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - "${PWD}/docker-data/v1/portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --admin-password $$2y$$05$$8w8V39N/QGvcqlQVAw46zeI.H2dcH15AoQrrHWV7c8CUQvY1uUkgi
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=(HostRegexp(`portainer.{.*}.ru`) || Host(`portainer.${my_local}`) || Host(`portainer.localhost`))      
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  web:
    external: true